library(shiny)

shinyServer(function(input, output) {
    sliderValues <- reactive({
      paste("NPV = ", -input$Integer0+
              (input$Integer1/(1+input$Decimal))+
              (input$Integer2/(1+input$Decimal)^2)+
              (input$Integer3/(1+input$Decimal)^3)+
              (input$Integer4/(1+input$Decimal)^4)+
              (input$Integer5/(1+input$Decimal)^5))
    })
      text1 <- reactive({
      paste("If NPV > 0, accept the project.
            If NPV = 0, Discount rate = IRR.
            IF NPV < 0, reject the project.")
      })
      text2 <- reactive({
        paste(
          "Net present value is the difference between the discounted present value of the future cash flows generated by an investment and the project investment cost. 
          It is an important indicator for a company to decide whether to invest in a project.
          IRR is the internal rate of return, which is the discount rate when net present value is equal to 0.
      Please enter the project's initial investment amount, annual cash flow, and estimated discount rate on the left.
          The NPV calculation is shown below."
        )
      })
    output$introduction <- renderText(
      text2()
    )
    output$conclusion <- renderText(
      text1()
    )
    output$answer <- renderText(
      sliderValues()
    )
})
